from app.models.atemschutz_pruefung import (
    AtemschutzGeraet,
    AtemschutzPruefBenachrichtigung,
    AtemschutzPruefung,
)
from app.models.breathing import BreathingTroop, PressureLog, TroopMember
from app.models.fahrtenbuch import (
    Fahrt,
    FahrtBenachrichtigung,
    FahrtErfassungsweg,
    FahrtKategorie,
    FahrtStatus,
    Fahrtzweck,
    Zielort,
)
from app.models.incident import (
    Incident,
    IncidentChange,
    IncidentColumn,
    IncidentLog,
    IncidentToken,
    IncidentVehicle,
    Message,
    RescuedPerson,
    Task,
)
from app.models.invitation import OrgInvitation, OrgPartner
from app.models.lagekarte import LagekarteToken
from app.models.lis import LisSyncedObject, OrgLisConfig
from app.models.major_incident import (
    CitizenReport,
    CommLogEntry,
    IncidentSite,
    MajorIncident,
    MajorIncidentStatus,
    Sector,
    SiteLogEntry,
    SiteMedia,
    SitePhase,
    SitePriority,
    SiteResourceAssignment,
    StaffAssignment,
    StaffFunction,
)
from app.models.media_annotation import MediaAnnotation, MediaAnnotationVersion
from app.models.master import (
    AIPromptVersion,
    AlarmType,
    DefaultMessage,
    DefaultMessageAlarm,
    FireDept,
    LageHint,
    LageHintAlarm,
    Member,
    MemberQualification,
    MessageSuggestion,
    MessageSuggestionAlarm,
    OrgStorageUsage,
    Qualification,
    SeedTemplate,
    TaskSuggestion,
    TaskSuggestionAlarm,
    VehicleMaster,
)
from app.models.objekt import (
    AlarmInfoscreenToken,
    GefahrenKatalog,
    InfoscreenUrl,
    MerkmalKatalog,
    Objekt,
    ObjektAuswahl,
    ObjektBMA,
    ObjektChange,
    ObjektDokument,
    ObjektDokumentSeite,
    ObjektEinsatz,
    ObjektGefahr,
    ObjektKartenObjekt,
    ObjektKategorie,
    ObjektKontakt,
    ObjektMerkmal,
    ObjektSeiteKiVorschlag,
    ObjektSymbol,
    ObjektWohnanlage,
    ObjektZusatzadresse,
)
from app.models.password_reset import PasswordResetToken
from app.models.sms import (
    SmsEinsatzinfoRecipient,
    SmsForwardRule,
    SmsForwardRuleGroup,
    SmsForwardRuleMember,
    SmsGroup,
    SmsGroupMember,
    SmsInbox,
    SmsLog,
)
from app.models.sso import OrgSsoConfig, OrgSsoGroupMap
from app.models.teams_bot import AlarmToken, TeamsAlarmConfig, TeamsCardPost, TeamsChannelBinding
from app.models.teilnahme import Funktion, Teilnahme, Termin
from app.models.uas import (
    UASCheckliste,
    UASDevice,
    UASEinsatz,
    UASEinsatzRolleEintrag,
    UASEreignis,
    UASFlug,
    UASFlugbewegung,
    UASKartenobjekt,
    UASMedien,
    UASPilot,
    UASWartung,
)
from app.models.user import (
    ApiKey,
    AuditLog,
    DeviceToken,
    FcmToken,
    PushLog,
    PushSubscription,
    Role,
    SmsGatewayToken,
    User,
    UserRole,
)
from app.models.verleih import (
    VerleihArtikel,
    VerleihAusleihe,
    VerleihFoto,
    VerleihPosition,
    VerleihStatus,
    VerleihStueckliste,
    VerleihStuecklistePosition,
)
from app.models.weather import WeatherReading, WeatherStation
from app.models.weather_alert import WeatherAlertLog, WeatherAlertRule, WeatherAlertState

__all__ = [
    "OrgSsoConfig", "OrgSsoGroupMap",
    "OrgLisConfig", "LisSyncedObject",
    "TeamsAlarmConfig", "TeamsChannelBinding", "TeamsCardPost", "AlarmToken",
    "User", "Role", "UserRole", "ApiKey", "AuditLog", "PushSubscription",
    "DeviceToken", "FcmToken", "PushLog", "SmsGatewayToken",
    "FireDept", "VehicleMaster", "Member", "Qualification", "MemberQualification",
    "AlarmType", "SeedTemplate", "AIPromptVersion", "OrgStorageUsage",
    "OrgInvitation", "OrgPartner",
    "TaskSuggestion", "TaskSuggestionAlarm",
    "MessageSuggestion", "MessageSuggestionAlarm",
    "LageHint", "LageHintAlarm", "DefaultMessage", "DefaultMessageAlarm",
    "Incident", "IncidentColumn", "IncidentVehicle", "Task", "Message",
    "RescuedPerson", "IncidentLog", "IncidentChange", "IncidentToken",
    "BreathingTroop", "TroopMember", "PressureLog",
    "PasswordResetToken",
    "LagekarteToken",
    "MajorIncident", "MajorIncidentStatus", "Sector", "StaffAssignment", "StaffFunction",
    "IncidentSite", "SitePhase", "SitePriority", "SiteResourceAssignment",
    "SiteLogEntry", "SiteMedia", "CommLogEntry", "CitizenReport",
    "VerleihArtikel", "VerleihStueckliste", "VerleihStuecklistePosition",
    "VerleihAusleihe", "VerleihPosition", "VerleihStatus", "VerleihFoto",
    "WeatherStation", "WeatherReading",
    "WeatherAlertRule", "WeatherAlertState", "WeatherAlertLog",
    "SmsGroup", "SmsGroupMember", "SmsEinsatzinfoRecipient", "SmsLog",
    "SmsInbox", "SmsForwardRule", "SmsForwardRuleGroup", "SmsForwardRuleMember",
    "Fahrtzweck", "Zielort", "Fahrt", "FahrtBenachrichtigung",
    "FahrtKategorie", "FahrtStatus", "FahrtErfassungsweg",
    "Termin", "Funktion", "Teilnahme",
    "Objekt", "ObjektKategorie", "ObjektZusatzadresse", "ObjektBMA", "ObjektChange",
    "GefahrenKatalog", "ObjektGefahr", "MerkmalKatalog", "ObjektMerkmal",
    "ObjektAuswahl", "ObjektKontakt", "ObjektWohnanlage",
    "ObjektDokument", "ObjektDokumentSeite", "ObjektKartenObjekt", "ObjektEinsatz",
    "ObjektSymbol", "AlarmInfoscreenToken", "InfoscreenUrl", "ObjektSeiteKiVorschlag",
    "UASDevice", "UASPilot", "UASFlugbewegung", "UASWartung",
    "UASEinsatz", "UASEinsatzRolleEintrag", "UASFlug", "UASCheckliste",
    "UASEreignis", "UASKartenobjekt", "UASMedien",
    "AtemschutzGeraet", "AtemschutzPruefung", "AtemschutzPruefBenachrichtigung",
    "MediaAnnotation", "MediaAnnotationVersion",
]
